import os
import json
import re
import time
import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)


def _get_deepseek_client():
    import openai
    return openai.OpenAI(
        api_key=os.getenv("DEEPSEEK_API_KEY"),
        base_url="https://api.deepseek.com/v1",
    )


# ─── Template fallback (no AI needed) ────────────────────────────
def _generate_template_docs(repo_name: str, files: List[Dict]) -> Dict[str, Any]:
    """Generate basic docs from file structure — used when all AI providers fail."""
    file_list = "\n".join(f"- `{f['file_path']}`" for f in files[:30])
    py_symbols = []
    for f in files:
        for s in f.get("symbols", []):
            py_symbols.append(f"- `{s['type']} {s['name']}`")
    symbols_section = "\n".join(py_symbols[:40]) if py_symbols else "_No symbols extracted._"

    readme = f"""# {repo_name.split('/')[-1]}

> Auto-generated documentation by **GhostDocs** 👻

## Overview

This repository contains the source code for **{repo_name}**.

## Project Structure

{file_list}

## Getting Started

```bash
git clone https://github.com/{repo_name}.git
cd {repo_name.split('/')[-1]}
```

## Symbols Detected

{symbols_section}

---
_Documentation generated by [GhostDocs](https://ghostdocs.pages.dev)_
"""

    api_docs = f"""# API Documentation — {repo_name.split('/')[-1]}

> Auto-generated by GhostDocs

## Detected Symbols

{symbols_section}

## Files

{file_list}
"""

    mermaid = "graph TD\n    A[Entry Point] --> B[Core Logic]\n    B --> C[Output]"

    return {"readme": readme, "api_docs": api_docs, "mermaid_diagram": mermaid}


class DocumentationAgent:
    def __init__(self, provider: str = None):
        self.provider = provider or os.getenv("LLM_PROVIDER", "gemini")
        self._gemini_ready = False
        self._gemini_model_name = "gemini-1.5-flash"

        if self.provider == "gemini":
            gemini_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
            if gemini_key:
                try:
                    import google.generativeai as genai
                    genai.configure(api_key=gemini_key)
                    # Pick fastest flash model
                    try:
                        models = [
                            m.name for m in genai.list_models()
                            if "generateContent" in m.supported_generation_methods
                        ]
                        flash = [m for m in models if "flash" in m and "1.5" in m]
                        if flash:
                            self._gemini_model_name = flash[0].replace("models/", "")
                    except Exception:
                        pass
                    self._gemini_ready = True
                    logger.info(f"[Agent] Gemini ready: {self._gemini_model_name}")
                except Exception as e:
                    logger.warning(f"[Agent] Gemini init failed: {e}")
            else:
                logger.warning("[Agent] GEMINI_API_KEY not set — Gemini disabled")

        elif self.provider == "openai":
            self._openai_key = os.getenv("OPENAI_API_KEY")

    # ─── JSON extraction ──────────────────────────────────────────
    def extract_json(self, text: str) -> Dict[str, Any]:
        if not text:
            raise ValueError("Empty response from AI")
        text = text.strip()
        for fence in ("```json", "```"):
            if text.startswith(fence):
                text = text.split(fence, 1)[1].rsplit("```", 1)[0].strip()
                break
        try:
            return json.loads(text)
        except Exception:
            pass
        start = text.find("{")
        end = text.rfind("}") + 1
        if start != -1 and end > start:
            try:
                return json.loads(text[start:end])
            except Exception:
                pass
        raise ValueError(f"No valid JSON. Got: {text[:200]}")

    # ─── DeepSeek ─────────────────────────────────────────────────
    def _try_deepseek(self, system_prompt: str, user_content: str) -> Dict[str, Any]:
        key = os.getenv("DEEPSEEK_API_KEY")
        if not key:
            raise RuntimeError("DEEPSEEK_API_KEY not set in environment")
        import openai
        client = openai.OpenAI(api_key=key, base_url="https://api.deepseek.com/v1")
        logger.info("[Agent] Calling DeepSeek...")
        resp = client.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
            response_format={"type": "json_object"},
            max_tokens=3000,
            temperature=0.1,
        )
        return self.extract_json(resp.choices[0].message.content)

    # ─── Gemini ───────────────────────────────────────────────────
    def _try_gemini(self, system_prompt: str, user_content: str) -> Dict[str, Any]:
        if not self._gemini_ready:
            raise RuntimeError("Gemini not initialized (missing API key)")
        import google.generativeai as genai
        model = genai.GenerativeModel(
            model_name=self._gemini_model_name,
            system_instruction=system_prompt,
        )
        logger.info(f"[Agent] Calling Gemini ({self._gemini_model_name})...")
        resp = model.generate_content(
            user_content,
            generation_config=genai.types.GenerationConfig(
                response_mime_type="application/json",
                max_output_tokens=3000,
                temperature=0.1,
            ),
        )
        return self.extract_json(resp.text)

    # ─── Main generation ──────────────────────────────────────────
    def generate_documentation(self, codebase_context: Dict[str, Any]) -> Dict[str, Any]:
        files = codebase_context.get("files", [])
        repo_name = "repository"

        system_prompt = (
            "You are a senior documentation engineer. "
            "Generate professional documentation for the provided codebase. "
            "Return a VALID JSON object with EXACTLY these keys: "
            '"readme" (full README.md in markdown), '
            '"api_docs" (API/function documentation), '
            '"mermaid_diagram" (valid Mermaid.js flowchart). '
            "Output ONLY raw JSON — no markdown fences, no extra text."
        )
        # Truncate to avoid token limits
        context_str = json.dumps({"files": files[:25]}, indent=1)
        if len(context_str) > 60000:
            context_str = context_str[:60000]
        user_content = f"Codebase:\n{context_str}"

        errors = []

        # ── Try Gemini first ──────────────────────────────────────
        try:
            result = self._try_gemini(system_prompt, user_content)
            logger.info("[Agent] Gemini succeeded ✅")
            return result
        except Exception as e:
            err = f"Gemini: {type(e).__name__}: {str(e)[:200]}"
            errors.append(err)
            logger.warning(f"[Agent] {err}")

        # ── Try DeepSeek ──────────────────────────────────────────
        try:
            result = self._try_deepseek(system_prompt, user_content)
            logger.info("[Agent] DeepSeek succeeded ✅")
            return result
        except Exception as e:
            err = f"DeepSeek: {type(e).__name__}: {str(e)[:200]}"
            errors.append(err)
            logger.warning(f"[Agent] {err}")

        # ── Template fallback (always works) ──────────────────────
        logger.warning(f"[Agent] All AI providers failed. Using template. Errors: {errors}")
        result = _generate_template_docs(repo_name, files)
        result["_fallback"] = True
        result["_errors"] = errors
        return result
