import os
import logging
from github import Github, GithubException
from typing import Dict, Any

logger = logging.getLogger(__name__)


class GitHubClient:
    def __init__(self, token: str = None):
        self.token = token or os.getenv("GITHUB_TOKEN")
        self.client = Github(self.token)

    def create_documentation_pr(
        self, repo_name: str, base_branch: str, docs: Dict[str, Any],
        commit_sha: str, job_id: str
    ) -> str:
        repo = self.client.get_repo(repo_name)
        new_branch_name = f"docs/ghostdocs-{job_id[:8]}"

        # ── Create new branch off base ──────────────────────────────
        try:
            source = repo.get_branch(base_branch)
        except GithubException as e:
            raise RuntimeError(f"Could not find branch '{base_branch}': {e.data.get('message', str(e))}")

        try:
            repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=source.commit.sha)
        except GithubException as e:
            raise RuntimeError(f"Could not create branch '{new_branch_name}': {e.data.get('message', str(e))}")

        # ── 1. README ───────────────────────────────────────────────
        readme = docs.get("readme")
        if readme:
            try:
                readme_content = repo.get_contents("README.md", ref=new_branch_name)
                repo.update_file(
                    "README.md", "docs: update README [GhostDocs]",
                    readme, readme_content.sha, branch=new_branch_name
                )
            except GithubException:
                try:
                    repo.create_file(
                        "README.md", "docs: create README [GhostDocs]",
                        readme, branch=new_branch_name
                    )
                except GithubException as e:
                    logger.error(f"[GitHub] Failed to write README for {repo_name}: {e}")

        # ── 2. API Docs ─────────────────────────────────────────────
        api_docs = docs.get("api_docs")
        if api_docs:
            try:
                try:
                    repo.create_file(
                        "docs/API.md", "docs: create API documentation [GhostDocs]",
                        api_docs, branch=new_branch_name
                    )
                except GithubException:
                    existing = repo.get_contents("docs/API.md", ref=new_branch_name)
                    repo.update_file(
                        "docs/API.md", "docs: update API documentation [GhostDocs]",
                        api_docs, existing.sha, branch=new_branch_name
                    )
            except GithubException as e:
                logger.error(f"[GitHub] Failed to write docs/API.md for {repo_name}: {e}")

        # ── 3. Open Pull Request ────────────────────────────────────
        try:
            pr = repo.create_pull(
                title=f"docs: GhostDocs auto-generated documentation [{commit_sha[:7]}]",
                body=(
                    "This PR was automatically generated by **GhostDocs** 👻\n\n"
                    "### What changed:\n"
                    "- ✅ Updated `README.md` with professional documentation\n"
                    "- ✅ Generated `docs/API.md` with full API reference\n"
                    "- ✅ Architecture diagram added\n\n"
                    "_Review, merge, and your docs are live!_"
                ),
                head=new_branch_name,
                base=base_branch,
            )
            return pr.html_url
        except GithubException as e:
            raise RuntimeError(f"Failed to create Pull Request: {e.data.get('message', str(e))}")
