import os
from github import Github
from typing import Dict, Any, List

HEADERS = {"User-Agent": "GhostDocs/1.0"}

class GitHubClient:
    def __init__(self, token: str = None):
        self.token = token or os.getenv("GITHUB_TOKEN")
        self.client = Github(self.token)

    def create_documentation_pr(self, repo_name: str, base_branch: str, docs: Dict[str, Any], commit_sha: str, job_id: str) -> str:
        repo = self.client.get_repo(repo_name)
        new_branch_name = f"docs/ghostdocs-{job_id[:8]}"
        
        # Create new branch
        source = repo.get_branch(base_branch)
        repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=source.commit.sha)

        # Update files
        # 1. README
        readme = docs.get("readme")
        if readme:
            try:
                readme_content = repo.get_contents("README.md", ref=new_branch_name)
                repo.update_file("README.md", "docs: update README [GhostDocs]", readme, 
                                 readme_content.sha, branch=new_branch_name)
            except:
                repo.create_file("README.md", "docs: create README [GhostDocs]", readme, branch=new_branch_name)
        
        # 2. API Docs
        api_docs = docs.get("api_docs")
        if api_docs:
            try:
                repo.create_file("docs/API.md", "docs: update API documentation [GhostDocs]", api_docs, branch=new_branch_name)
            except:
                try:
                    repo.update_file("docs/API.md", "docs: update API documentation [GhostDocs]", api_docs, 
                                     repo.get_contents("docs/API.md", ref=new_branch_name).sha, branch=new_branch_name)
                except Exception as e:
                    print(f"Error updating docs/API.md: {e}")

        # 3. Inline comments (this is tricky, usually we'd patch files)
        for item in docs.get("inline_comments", []):
            path = item["file_path"]
            content = item["code_with_comments"]
            try:
                repo.update_file(path, f"docs: add inline comments to {path} [GhostDocs]", content, 
                                 repo.get_contents(path, ref=new_branch_name).sha, branch=new_branch_name)
            except Exception as e:
                print(f"Error updating {path}: {e}")

        # Create PR
        pr = repo.create_pull(
            title=f"docs: GhostDocs auto-update [{commit_sha[:7]}]",
            body="This PR was automatically generated by GhostDocs.\n\n### Changes:\n- Updated README\n- Generated API documentation\n- Added inline comments\n- Updated architecture diagram",
            head=new_branch_name,
            base=base_branch
        )
        return pr.html_url
